<script setup>

import { appStore } from "@/stores/App";
const store = appStore();

</script>


<template>

    <div v-if="store.isLoading" class="loading">
        
        <div> 
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<rect x="19" y="33" width="12" height="34" fill="#0099e5">
  <animate attributeName="y" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="16;33;33" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.3278688524590164s"></animate>
  <animate attributeName="height" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="68;34;34" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.3278688524590164s"></animate>
</rect>
<rect x="44" y="33" width="12" height="34" fill="#ff4c4c">
  <animate attributeName="y" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="20.25;33;33" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.1639344262295082s"></animate>
  <animate attributeName="height" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="59.5;34;34" keySplines="0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.1639344262295082s"></animate>
</rect>
<rect x="69" y="33" width="12" height="34" fill="#34bf49">
  <animate attributeName="y" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="20.25;33;33" keySplines="0 0.5 0.5 1;0 0.5 0.5 1"></animate>
  <animate attributeName="height" repeatCount="indefinite" dur="1.639344262295082s" calcMode="spline" keyTimes="0;0.5;1" values="59.5;34;34" keySplines="0 0.5 0.5 1;0 0.5 0.5 1"></animate>
</rect>
<!-- [ldio] generated by https://loading.io/ --></svg>
        </div>
        
        <p> 
            
            
            Yükleniyor...</p>
        
    </div>

</template>

<style scoped>


.loading{
	position:   fixed;
	z-index:    100000;
	top:        0;
	left:       0;
	height:     100%;
	width:      100%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: aliceblue;
    font-size: xx-large;
	background: rgba(25, 24, 24, 0.8);
}

</style>

